# ~/.zshenv — sourced by every zsh, before anything else.
#
# Must live at $HOME: zsh reads it first and only then honours ZDOTDIR.
# Everything else lives in $ZDOTDIR (.config/zsh).
#
# Also sourced by bash from scripts/commit-and-push.sh, so keep it POSIX-ish:
# no zsh-only syntax outside the ZSH_VERSION guard at the bottom.

export ZDOTDIR="$HOME/.config/zsh"

# --- PATH ---
#
# One assignment, highest priority first. The old version used a sequence of
# prepends, which meant the LAST line won and ~/.local/bin — the one directory
# that should outrank Homebrew — ended up last.
#
# ./bin is deliberately gone. It put the bin/ of whatever repo you happened to
# be standing in ahead of your own scripts, including repos cloned by agents.
# Use direnv's `PATH_add bin` per project instead; it is hooked in .zshrc.
PATH="$HOME/.local/bin:$HOME/.bin:$HOME/.gem/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$HOME/go/bin:$PATH"
export PATH

# --- Ruby ---
# Gems go to a version-independent directory. Homebrew's own gem bin path is
# /opt/homebrew/lib/ruby/gems/<MAJOR.MINOR.0>/bin, which silently breaks on
# every ruby upgrade — it was still pinned to 3.4.0 while ruby was 4.0.
export GEM_HOME="$HOME/.gem"

# --- Locale ---
export LC_ALL=en_US.UTF-8

# --- Editor ---
export EDITOR=nvim

# --- FZF ---
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
# Colours come from $ZDOTDIR/fzf-colors.zsh, generated by scripts/theme.sh.

# --- Tools ---
#
# BAT_THEME is deliberately NOT set. It used to be `base16`, which also pinned
# git-delta's syntax-theme (delta reads BAT_THEME) and stopped both tools from
# following the system appearance. The whole bat story now lives in
# ~/.config/bat/config, generated from the theme's meta.sh — one source, not two.
export GPG_TTY=$(tty)

# zsh-only tail. `|| :` so sourcing this from bash (commit-and-push.sh) still
# returns 0 — the test itself fails there and would otherwise look like an error.
if [ -n "${ZSH_VERSION:-}" ]; then
  # Deduplicate, keeping the leftmost occurrence...
  typeset -U path
  # ...then drop entries whose directory no longer exists. This is what clears
  # stale inherited entries (~/.asdf/shims, ./bin, an old gems/X.Y.0 path)
  # instead of carrying them until the next logout.
  # Hidden behind eval: bash parses this whole file when commit-and-push.sh
  # sources it, and zsh glob qualifiers are a bash parse error even inside a
  # branch bash never takes.
  eval 'path=($^path(N-/))'
fi
:
