#!/bin/bash

export SYSTEM_TYPE=$(uname -s)

export BOOTSTRAP_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $BOOTSTRAP_DIR


case "$OSTYPE" in
	darwin*)
  		echo "Bootstraping Xcode"
  		./scripts/xcode.sh

  		echo "Bootstraping macOS"
  		./scripts/macos.sh

  		echo "Bootstraping Homebrew"
  		./scripts/homebrew.sh

    		echo "Bootstraping whalebrew"
  		./scripts/whalebrew.sh

  		sudo xcodebuild -license

  		echo "Bootstraping dnsmasq"
  		./scripts/dnsmasq.sh
		
		echo "Bootstrapping iTerm2"
		./scripts/iterm.sh
		;;
	
	linux*)
  		echo "Bootstraping Linux"
  		./scripts/linux.sh
		;;
	*) ;;
esac


echo "Boostrapping ZSH"
./scripts/zsh.sh

echo "Bootstraping asdf"
./scripts/asdf.sh

# echo "Bootstraping Rust"
# ./scripts/rust.sh

echo "Bootstraping Cron"
./scripts/cron.sh

echo "Bootstraping Emacs"
./scripts/emacs.sh

echo "Bootstraping tmux"
./scripts/tmux.sh


if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  for app in "Dock" "Finder" "Mail" "Messages" "Safari" "SystemUIServer" "Terminal"; do
   killall "${app}" > /dev/null 2>&1
  done
fi
