# Generated by scripts/theme.sh — do not edit.
#
# --color=16 plus -1 (terminal default) for fg/bg, so fzf inherits the live
# palette and follows a light/dark flip without being told.
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --color=16 --color=fg:-1,bg:-1,hl:4,fg+:-1,bg+:8,hl+:12,info:6,prompt:2,pointer:5,marker:3,spinner:6,header:8,border:8,gutter:-1'
