# Generated by scripts/theme.sh — Ghostty app icon, tinted from the palette.
#
# Included from the tracked config via `config-file = ?icon.conf`.
#
# custom-style takes the official artist-made icon and recolours two of its
# layers, so the Dock icon follows whichever theme is active. It is marked
# EXPERIMENTAL upstream — the layer set may change. If it ever breaks, replace
# this whole file with one of the fixed variants:
#
#   macos-icon = blueprint | chalkboard | microchip | glass
#              | holographic | paper | retro | xray | official
#
# Only ONE colour pair is emitted, not one per mode: NSApplication.icon is a
# single image and does not switch with the system appearance. The dark
# palette's accent reads better against every Dock background, so it wins.
#
# Caveat from Ghostty's docs: this sets the Dock / app-switcher / Cmd-Tab icon.
# The FINDER icon is baked into the signed app bundle and cannot change at
# runtime.
macos-icon = custom-style
macos-icon-frame = chrome
macos-icon-ghost-color = {{D_ACCENT}}
macos-icon-screen-color = {{D_BACKGROUND}}
