# Generated by scripts/theme.sh — do not edit; edit the palette instead.
# {{NAME}}
background = {{BACKGROUND}}
foreground = {{FOREGROUND}}
cursor-color = {{CURSOR}}
cursor-text = {{CURSOR_TEXT}}
selection-background = {{SELECTION_BG}}
selection-foreground = {{SELECTION_FG}}
palette = 0={{ANSI_00}}
palette = 1={{ANSI_01}}
palette = 2={{ANSI_02}}
palette = 3={{ANSI_03}}
palette = 4={{ANSI_04}}
palette = 5={{ANSI_05}}
palette = 6={{ANSI_06}}
palette = 7={{ANSI_07}}
palette = 8={{ANSI_08}}
palette = 9={{ANSI_09}}
palette = 10={{ANSI_10}}
palette = 11={{ANSI_11}}
palette = 12={{ANSI_12}}
palette = 13={{ANSI_13}}
palette = 14={{ANSI_14}}
palette = 15={{ANSI_15}}
