# Generated by scripts/theme.sh from htoprc.base + meta.sh — do not edit.
#
# htop has no theme file, only color_scheme 0..6, so this file IS the theme.
# The `htop` wrapper in functions.zsh points HTOPRC here, which also means
# htop's write-back-on-exit lands in this generated file rather than in the
# tracked htoprc.base.
{{HTOPRC_BASE}}
color_scheme={{HTOP_SCHEME}}
