# Generated by scripts/theme.sh — ANSI fallback skin.
#
# Used when COLORTERM is unset (no truecolor), where the hex skin would render
# wrong. Colour names resolve through the terminal's live palette, so this one
# follows a light/dark flip for free.
[skin]
    description = yadm (ANSI)
    truecolors = false

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼

[core]
    _default_ = default;default
    selected = black;blue
    marked = yellow;default;bold
    markselect = yellow;blue;bold
    gauge = blue;default
    input = default;default
    inputunchanged = gray;default
    inputmark = black;blue
    disabled = gray;default
    reverse = black;white
    header = brightblue;default;bold
    shadow = gray;default

[dialog]
    _default_ = default;default
    dfocus = black;blue
    dhotnormal = brightblue;default;underline
    dhotfocus = brightblue;blue;underline
    dtitle = brightblue;default;bold

[error]
    _default_ = white;red
    errdfocus = white;brightred
    errdhotnormal = white;red;underline
    errdhotfocus = white;brightred;underline
    errdtitle = white;red;bold

[filehighlight]
    directory = brightblue
    executable = green
    symlink = cyan
    stalelink = red
    device = magenta
    special = yellow
    archive = magenta
    doc = cyan
    source = yellow
    media = brightblue
    graph = brightcyan
    database = brightyellow
    temp = gray

[menu]
    _default_ = default;default
    menusel = black;blue
    menuhot = brightblue;default;underline
    menuhotsel = brightblue;blue;underline
    menuinactive = gray;default

[buttonbar]
    hotkey = black;blue
    button = default;default

[statusbar]
    _default_ = gray;default

[editor]
    _default_ = default;default
    editbold = red;default;bold
    editmarked = black;blue
    editwhitespace = gray;default
    editlinestate = gray;default

[viewer]
    _default_ = default;default
    viewbold = red;default;bold
    viewunderline = brightblue;default;underline
    viewselected = black;blue
