# Generated by scripts/theme.sh — {{NAME}}
#
# Truecolor mc skin. Requires mc built against S-Lang (4.8.19+), a 256-colour
# TERM, and COLORTERM=truecolor or 24bit — the `mc` wrapper in functions.zsh
# selects this file via MC_SKIN and falls back to yadm-ansi when COLORTERM is
# unset. Colour syntax is: foreground;background;attributes
[skin]
    description = {{NAME}}
    truecolors = true

[Lines]
    horiz = ─
    vert = │
    lefttop = ┌
    righttop = ┐
    leftbottom = └
    rightbottom = ┘
    topmiddle = ┬
    bottommiddle = ┴
    leftmiddle = ├
    rightmiddle = ┤
    cross = ┼
    dhoriz = ═
    dvert = ║
    dlefttop = ╔
    drighttop = ╗
    dleftbottom = ╚
    drightbottom = ╝
    dtopmiddle = ╤
    dbottommiddle = ╧
    dleftmiddle = ╟
    drightmiddle = ╢

[core]
    _default_ = {{FOREGROUND}};{{BACKGROUND}}
    selected = {{SELECTION_FG}};{{SELECTION_BG}}
    marked = {{ANSI_03}};{{BACKGROUND}};bold
    markselect = {{ANSI_03}};{{SELECTION_BG}};bold
    gauge = {{ACCENT}};{{BACKGROUND_DARKER}}
    input = {{FOREGROUND}};{{BACKGROUND_DARKER}}
    inputunchanged = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}
    inputmark = {{SELECTION_FG}};{{SELECTION_BG}}
    disabled = {{FOREGROUND_DIM}};{{BACKGROUND}}
    reverse = {{BACKGROUND}};{{FOREGROUND}}
    commandlinemark = {{SELECTION_FG}};{{SELECTION_BG}}
    header = {{ACCENT}};{{BACKGROUND}};bold
    shadow = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}

[dialog]
    _default_ = {{FOREGROUND}};{{BACKGROUND_LIGHTER}}
    dfocus = {{SELECTION_FG}};{{SELECTION_BG}}
    dhotnormal = {{ACCENT}};{{BACKGROUND_LIGHTER}};underline
    dhotfocus = {{ACCENT}};{{SELECTION_BG}};underline
    dtitle = {{ACCENT}};{{BACKGROUND_LIGHTER}};bold

[error]
    _default_ = {{BACKGROUND}};{{SYN_ERROR}}
    errdfocus = {{BACKGROUND}};{{ANSI_09}}
    errdhotnormal = {{BACKGROUND}};{{SYN_ERROR}};underline
    errdhotfocus = {{BACKGROUND}};{{ANSI_09}};underline
    errdtitle = {{BACKGROUND}};{{SYN_ERROR}};bold

[filehighlight]
    directory = {{ACCENT}}
    executable = {{ANSI_02}}
    symlink = {{ANSI_06}}
    hardlink = {{FOREGROUND}}
    stalelink = {{SYN_ERROR}}
    device = {{ANSI_05}}
    special = {{ANSI_03}}
    core = {{ANSI_09}}
    temp = {{FOREGROUND_DIM}}
    archive = {{ANSI_05}}
    doc = {{ANSI_06}}
    source = {{ANSI_03}}
    media = {{ANSI_12}}
    graph = {{ANSI_14}}
    database = {{ANSI_11}}

[menu]
    _default_ = {{FOREGROUND}};{{BACKGROUND_DARKER}}
    menusel = {{SELECTION_FG}};{{SELECTION_BG}}
    menuhot = {{ACCENT}};{{BACKGROUND_DARKER}};underline
    menuhotsel = {{ACCENT}};{{SELECTION_BG}};underline
    menuinactive = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}

[popupmenu]
    _default_ = {{FOREGROUND}};{{BACKGROUND_LIGHTER}}
    menusel = {{SELECTION_FG}};{{SELECTION_BG}}
    menutitle = {{ACCENT}};{{BACKGROUND_LIGHTER}};bold

[buttonbar]
    hotkey = {{BACKGROUND}};{{ACCENT}}
    button = {{FOREGROUND}};{{BACKGROUND_DARKER}}

[statusbar]
    _default_ = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}

[help]
    _default_ = {{FOREGROUND}};{{BACKGROUND_LIGHTER}}
    helpbold = {{ACCENT}};{{BACKGROUND_LIGHTER}};bold
    helpitalic = {{ANSI_06}};{{BACKGROUND_LIGHTER}};italic
    helplink = {{ACCENT_ALT}};{{BACKGROUND_LIGHTER}};underline
    helpslink = {{SELECTION_FG}};{{SELECTION_BG}}

[editor]
    _default_ = {{FOREGROUND}};{{BACKGROUND}}
    editbold = {{SYN_KEYWORD}};{{BACKGROUND}};bold
    editmarked = {{SELECTION_FG}};{{SELECTION_BG}}
    editwhitespace = {{FOREGROUND_DIM}};{{BACKGROUND}}
    editlinestate = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}
    bookmark = {{BACKGROUND}};{{ANSI_03}}
    bookmarkfound = {{BACKGROUND}};{{ANSI_02}}
    editrightmargin = {{FOREGROUND_DIM}};{{BACKGROUND_DARKER}}
    editbg = ;{{BACKGROUND}}
    editframe = {{BORDER}};{{BACKGROUND}}
    editframeactive = {{ACCENT}};{{BACKGROUND}}
    editframedrag = {{ACCENT_ALT}};{{BACKGROUND}}

[viewer]
    _default_ = {{FOREGROUND}};{{BACKGROUND}}
    viewbold = {{SYN_KEYWORD}};{{BACKGROUND}};bold
    viewunderline = {{ACCENT}};{{BACKGROUND}};underline
    viewselected = {{SELECTION_FG}};{{SELECTION_BG}}

[diffviewer]
    changedline = {{SYN_DIFF_CHANGE}};{{BACKGROUND}}
    changednew = {{SYN_DIFF_ADD}};{{BACKGROUND}}
    changed = {{SYN_DIFF_CHANGE}};{{BACKGROUND_DARKER}}
    added = {{SYN_DIFF_ADD}};{{BACKGROUND_DARKER}}
    removed = {{SYN_DIFF_DEL}};{{BACKGROUND_DARKER}}
    error = {{BACKGROUND}};{{SYN_ERROR}}

[widget-scollbar]
    scroll-bar = {{BORDER}};{{BACKGROUND}}
    scroll-button = {{ACCENT}};{{BACKGROUND}}
