-- Generated by scripts/theme.sh — {{NAME}}. Do not edit; edit the palette.
--
-- A plain highlight-group colorscheme built from the palette's SYN_* roles.
-- It is deliberately flatter than a hand-tuned theme: ~14 roles cannot
-- reproduce the hundreds of groups in onedark or github-nvim-theme. Revert to
-- those with `theme.sh render --skip editors`.
local M = {}

local c = {
  bg          = "{{BACKGROUND}}",
  bg_dark     = "{{BACKGROUND_DARKER}}",
  bg_light    = "{{BACKGROUND_LIGHTER}}",
  fg          = "{{FOREGROUND}}",
  fg_dim      = "{{FOREGROUND_DIM}}",
  sel_bg      = "{{SELECTION_BG}}",
  sel_fg      = "{{SELECTION_FG}}",
  cursor      = "{{CURSOR}}",
  border      = "{{BORDER}}",
  accent      = "{{ACCENT}}",
  accent_alt  = "{{ACCENT_ALT}}",
  comment     = "{{SYN_COMMENT}}",
  string      = "{{SYN_STRING}}",
  keyword     = "{{SYN_KEYWORD}}",
  func        = "{{SYN_FUNCTION}}",
  type        = "{{SYN_TYPE}}",
  constant    = "{{SYN_CONSTANT}}",
  variable    = "{{SYN_VARIABLE}}",
  operator    = "{{SYN_OPERATOR}}",
  error       = "{{SYN_ERROR}}",
  warning     = "{{SYN_WARNING}}",
  hint        = "{{SYN_HINT}}",
  add         = "{{SYN_DIFF_ADD}}",
  del         = "{{SYN_DIFF_DEL}}",
  change      = "{{SYN_DIFF_CHANGE}}",
}

M.colors = c

function M.load()
  vim.cmd("highlight clear")
  if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
  vim.o.background = "{{MODE}}"
  vim.g.colors_name = "yadm-{{MODE}}"

  local hl = function(group, spec) vim.api.nvim_set_hl(0, group, spec) end

  -- Transparency is preserved: the original config set bg = "NONE" on ~45
  -- groups so the terminal background shows through. Keep that.
  hl("Normal",       { fg = c.fg, bg = "NONE" })
  hl("NormalNC",     { fg = c.fg, bg = "NONE" })
  hl("NormalFloat",  { fg = c.fg, bg = "NONE" })
  hl("FloatBorder",  { fg = c.border, bg = "NONE" })
  hl("SignColumn",   { bg = "NONE" })
  hl("EndOfBuffer",  { fg = c.bg_dark, bg = "NONE" })
  hl("VertSplit",    { fg = c.border, bg = "NONE" })
  hl("WinSeparator", { fg = c.border, bg = "NONE" })

  hl("Cursor",       { fg = c.bg, bg = c.cursor })
  hl("CursorLine",   { bg = c.bg_dark })
  hl("CursorLineNr", { fg = c.accent, bold = true })
  hl("LineNr",       { fg = c.fg_dim })
  hl("Visual",       { fg = c.sel_fg, bg = c.sel_bg })
  hl("Search",       { fg = c.bg, bg = c.warning })
  hl("IncSearch",    { fg = c.bg, bg = c.accent })
  hl("MatchParen",   { fg = c.accent, bold = true })
  hl("ColorColumn",  { bg = c.bg_dark })
  hl("Folded",       { fg = c.fg_dim, bg = c.bg_dark })
  hl("Pmenu",        { fg = c.fg, bg = c.bg_dark })
  hl("PmenuSel",     { fg = c.sel_fg, bg = c.sel_bg })
  hl("StatusLine",   { fg = c.fg, bg = "NONE" })
  hl("StatusLineNC", { fg = c.fg_dim, bg = "NONE" })
  hl("TabLine",      { fg = c.fg_dim, bg = "NONE" })
  hl("TabLineSel",   { fg = c.accent, bg = "NONE", bold = true })
  hl("TabLineFill",  { bg = "NONE" })
  hl("Title",        { fg = c.accent, bold = true })
  hl("Directory",    { fg = c.accent })
  hl("NonText",      { fg = c.fg_dim })
  hl("Whitespace",   { fg = c.border })

  -- syntax
  hl("Comment",      { fg = c.comment, italic = true })
  hl("String",       { fg = c.string })
  hl("Character",    { fg = c.string })
  hl("Number",       { fg = c.constant })
  hl("Boolean",      { fg = c.constant })
  hl("Float",        { fg = c.constant })
  hl("Constant",     { fg = c.constant })
  hl("Identifier",   { fg = c.variable })
  hl("Function",     { fg = c.func })
  hl("Statement",    { fg = c.keyword })
  hl("Conditional",  { fg = c.keyword })
  hl("Repeat",       { fg = c.keyword })
  hl("Label",        { fg = c.keyword })
  hl("Operator",     { fg = c.operator })
  hl("Keyword",      { fg = c.keyword })
  hl("Exception",    { fg = c.keyword })
  hl("PreProc",      { fg = c.accent_alt })
  hl("Include",      { fg = c.accent_alt })
  hl("Define",       { fg = c.accent_alt })
  hl("Macro",        { fg = c.accent_alt })
  hl("Type",         { fg = c.type })
  hl("StorageClass", { fg = c.type })
  hl("Structure",    { fg = c.type })
  hl("Typedef",      { fg = c.type })
  hl("Special",      { fg = c.accent_alt })
  hl("Delimiter",    { fg = c.fg })
  hl("Todo",         { fg = c.bg, bg = c.warning, bold = true })
  hl("Error",        { fg = c.error })
  hl("Underlined",   { fg = c.accent, underline = true })

  -- treesitter
  hl("@comment",            { link = "Comment" })
  hl("@string",             { link = "String" })
  hl("@number",             { link = "Number" })
  hl("@boolean",            { link = "Boolean" })
  hl("@function",           { link = "Function" })
  hl("@function.call",      { link = "Function" })
  hl("@function.builtin",   { fg = c.func, italic = true })
  hl("@method",             { link = "Function" })
  hl("@keyword",            { link = "Keyword" })
  hl("@keyword.function",   { link = "Keyword" })
  hl("@keyword.return",     { link = "Keyword" })
  hl("@type",               { link = "Type" })
  hl("@type.builtin",       { fg = c.type, italic = true })
  hl("@variable",           { fg = c.variable })
  hl("@variable.builtin",   { fg = c.keyword, italic = true })
  hl("@variable.parameter", { fg = c.fg })
  hl("@property",           { fg = c.variable })
  hl("@field",              { fg = c.variable })
  hl("@constant",           { link = "Constant" })
  hl("@constructor",        { fg = c.type })
  hl("@operator",           { link = "Operator" })
  hl("@punctuation.bracket",     { fg = c.fg })
  hl("@punctuation.delimiter",   { fg = c.fg })
  hl("@tag",                { fg = c.keyword })
  hl("@tag.attribute",      { fg = c.type })

  -- diagnostics
  hl("DiagnosticError", { fg = c.error })
  hl("DiagnosticWarn",  { fg = c.warning })
  hl("DiagnosticInfo",  { fg = c.accent })
  hl("DiagnosticHint",  { fg = c.hint })
  hl("DiagnosticUnderlineError", { undercurl = true, sp = c.error })
  hl("DiagnosticUnderlineWarn",  { undercurl = true, sp = c.warning })
  hl("DiagnosticUnderlineInfo",  { undercurl = true, sp = c.accent })
  hl("DiagnosticUnderlineHint",  { undercurl = true, sp = c.hint })

  -- diff / git
  hl("DiffAdd",      { fg = c.add })
  hl("DiffChange",   { fg = c.change })
  hl("DiffDelete",   { fg = c.del })
  hl("DiffText",     { fg = c.change, bold = true })
  hl("Added",        { fg = c.add })
  hl("Changed",      { fg = c.change })
  hl("Removed",      { fg = c.del })
  hl("GitSignsAdd",    { fg = c.add })
  hl("GitSignsChange", { fg = c.change })
  hl("GitSignsDelete", { fg = c.del })

  -- plugins that the old config also made transparent
  hl("TelescopeNormal",       { fg = c.fg, bg = "NONE" })
  hl("TelescopeBorder",       { fg = c.border, bg = "NONE" })
  hl("TelescopeSelection",    { fg = c.sel_fg, bg = c.sel_bg })
  hl("TelescopeMatching",     { fg = c.accent, bold = true })
  hl("NeoTreeNormal",         { fg = c.fg, bg = "NONE" })
  hl("NeoTreeNormalNC",       { fg = c.fg, bg = "NONE" })
  hl("NvimTreeNormal",        { fg = c.fg, bg = "NONE" })
  hl("WhichKeyFloat",         { bg = "NONE" })
  hl("LazyNormal",            { bg = "NONE" })
  hl("MasonNormal",           { bg = "NONE" })
end

return M
