# Generated by scripts/theme.sh — do not edit.
#
# ANSI indices only, never hex. The terminal swaps its own palette when macOS
# flips appearance, so these repaint in already-running sessions on the next
# redraw with no reload and no daemon. `bg=default` is the load-bearing part:
# it makes tmux inherit the live terminal background instead of painting one.
set -g status-style 'fg=colour7,bg=default'
set -g status-left-style 'fg=colour4,bold'
set -g status-right-style 'fg=colour8'
set -g window-status-style 'fg=colour8,bg=default'
set -g window-status-current-style 'fg=colour2,bg=default,bold'
set -g window-status-activity-style 'fg=colour3,bg=default'
set -g pane-border-style 'fg=colour8'
set -g pane-active-border-style 'fg=colour4'
set -g message-style 'fg=colour3,bg=default'
set -g message-command-style 'fg=colour3,bg=default'
set -g mode-style 'fg=colour0,bg=colour4'
set -g clock-mode-colour colour4
set -g copy-mode-match-style 'fg=colour0,bg=colour3'
set -g copy-mode-current-match-style 'fg=colour0,bg=colour2'
