{
  "$comment": "Generated by scripts/theme.sh. VS Code can only load a colour theme from an extension, never from a bare JSON path, so this minimal extension is the delivery mechanism.",
  "name": "yadm-theme",
  "displayName": "yadm theme",
  "description": "Generated from the yadm dotfiles palette.",
  "version": "1.0.0",
  "publisher": "local",
  "engines": { "vscode": "^1.70.0" },
  "categories": ["Themes"],
  "contributes": {
    "themes": [
      { "label": "yadm Light", "uiTheme": "vs",     "path": "./themes/yadm-light.json" },
      { "label": "yadm Dark",  "uiTheme": "vs-dark", "path": "./themes/yadm-dark.json" }
    ]
  }
}
