tap 'homebrew/cask-cask'
tap 'homebrew/cask-versions'
tap 'homebrew/cask-fonts'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'bat'
brew 'blockblock'
brew 'cloc'
brew 'diff-so-fancy'
brew 'dnsmasq', restart_service: true
brew 'git'
brew 'ffmpeg'
brew 'hivemind'
brew 'jq'
brew 'mas'
brew 'moreutils'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'speedtest-cli'
brew 'the_silver_searcher'
# brew 'watchman'
brew 'whalebrew'
brew 'yadm'
brew 'zopfli'

# cask 'android-studio'
cask 'alfred'
cask 'arq'
cask 'appcleaner'
# cask 'cocoarestclient
cask 'docker'
cask 'dropbox'
cask 'dropshare'
cask 'firefox'
cask 'fliqlo'
cask 'focus'
# cask 'fork'
# cask 'genymotion'
# cask 'google-chrome'
cask 'guitar-pro'
cask 'iina'
cask 'imagealpha'
cask 'imageoptim'
# cask 'java'
cask 'karabiner-elements'
cask 'keybase'
cask 'little-snitch'
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'webpquicklook'
# cask 'react-native-debugger'
# cask 'sketch'
cask 'spectacle'
cask 'visual-studio-code'
cask 'tomighty'
cask 'transmission'
cask 'viscosity'
cask 'vlc'
cask 'zoomus'

cask 'font-jetbrains-mono'

mas '1Password', id: 443987910
mas 'Amphetamine', id: 937984704
mas 'AudioBookBinder', id: 413969927
mas 'DaisyDisk', id: 411643860
# mas 'Day One', id: 1055511498
# mas 'Daum Equation Editor', id: 540665783
mas 'Euclid', id: 656423396
# mas 'Flashcard Hero', id: 650802274
mas 'Garage Band', id: 682658836
mas 'The Unarchiver', id: 425424353
mas 'Metronome X', id: 1222424189
mas 'MindNode', id: 992076693
mas 'Pixel Winch', id: 735066709
mas 'Readkit', id: 588726889
mas 'Slack', id: 803453959
mas 'Telegram', id: 747648890
mas 'Things3', id: 904280696
mas 'Xcode', id: 497799835
