-- Tracked shim so `:colorscheme yadm-dark` works like any other colorscheme.
-- The actual highlight groups live in lua/yadm-theme/dark.lua, which is
-- GENERATED by scripts/theme.sh from the palette and is gitignored.
local ok, theme = pcall(require, "yadm-theme.dark")
if not ok then
  vim.notify("yadm-theme.dark missing — run: theme.sh render", vim.log.levels.WARN)
  return
end
theme.load()
