-- Colorscheme.
--
-- The active themes are yadm-light / yadm-dark, generated by scripts/theme.sh
-- from .config/yadm/themes/<name>/palette.*.sh. They are flatter than the two
-- hand-tuned themes below, which is the accepted trade for having one palette
-- drive the terminal, tmux, fzf, btop, mc, VS Code, Zed and Alfred as well.
--
-- To revert: render with `theme.sh render --skip editors`, then swap the two
-- colorscheme names in this file back to onedark / github_light_default. Both
-- plugins are still installed for exactly that reason.
return {
  -- Kept, lazily, as the revert path.
  { "projekt0n/github-nvim-theme", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "yadm-dark",
    },
  },

  -- Auto-switch on system appearance. This is what makes the generated pair
  -- follow macOS without a daemon: the plugin polls AppleInterfaceStyle and
  -- each mode has its own generated colorscheme.
  {
    "f-person/auto-dark-mode.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      local auto_dark_mode = require("auto-dark-mode")

      auto_dark_mode.setup({
        update_interval = 1000,
        set_dark_mode = function()
          vim.o.background = "dark"
          pcall(vim.cmd, "colorscheme yadm-dark")
        end,
        set_light_mode = function()
          vim.o.background = "light"
          pcall(vim.cmd, "colorscheme yadm-light")
        end,
      })

      auto_dark_mode.init()
    end,
  },
}
